"""create users and cars tables

Revision ID: e801aa014082
Revises:
Create Date: 2026-03-15 18:20:36.177792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e801aa014082"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("brand_raw", sa.String(length=255), nullable=True),
        sa.Column("brand_normalized", sa.String(length=255), nullable=True),
        sa.Column("model_raw", sa.String(length=255), nullable=True),
        sa.Column("model_normalized", sa.String(length=255), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("price_jpy", sa.Integer(), nullable=True),
        sa.Column("total_price_jpy", sa.Integer(), nullable=True),
        sa.Column("location_raw", sa.String(length=255), nullable=True),
        sa.Column("location_normalized", sa.String(length=255), nullable=True),
        sa.Column("fuel_raw", sa.String(length=255), nullable=True),
        sa.Column("fuel_normalized", sa.String(length=255), nullable=True),
        sa.Column("transmission_raw", sa.String(length=255), nullable=True),
        sa.Column("transmission_normalized", sa.String(length=255), nullable=True),
        sa.Column("body_type_raw", sa.String(length=255), nullable=True),
        sa.Column("body_type_normalized", sa.String(length=255), nullable=True),
        sa.Column("color_raw", sa.String(length=255), nullable=True),
        sa.Column("dealer_name", sa.String(length=255), nullable=True),
        sa.Column("main_image_url", sa.Text(), nullable=True),
        sa.Column("image_urls", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("specs", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cars_brand_normalized"), "cars", ["brand_normalized"], unique=False
    )
    op.create_index(op.f("ix_cars_external_id"), "cars", ["external_id"], unique=True)
    op.create_index(op.f("ix_cars_mileage_km"), "cars", ["mileage_km"], unique=False)
    op.create_index(
        op.f("ix_cars_model_normalized"), "cars", ["model_normalized"], unique=False
    )
    op.create_index(op.f("ix_cars_price_jpy"), "cars", ["price_jpy"], unique=False)
    op.create_index(op.f("ix_cars_year"), "cars", ["year"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_cars_year"), table_name="cars")
    op.drop_index(op.f("ix_cars_price_jpy"), table_name="cars")
    op.drop_index(op.f("ix_cars_model_normalized"), table_name="cars")
    op.drop_index(op.f("ix_cars_mileage_km"), table_name="cars")
    op.drop_index(op.f("ix_cars_external_id"), table_name="cars")
    op.drop_index(op.f("ix_cars_brand_normalized"), table_name="cars")
    op.drop_table("cars")
    # ### end Alembic commands ###
